// https://docs.oracle.com/cd/E41183_01/DR/Date_Format_Types.html
export const DATE_FORMATS = [
  "D/M/YYYY",
  "D/MM/YYYY",
  "DD/M/YYYY",
  "DD/MM/YYYY",
  "M/D/YYYY",
  "M/DD/YYYY",
  "MM/D/YYYY",
  "MM/DD/YYYY",
  "YYYY/M/D",
  "YYYY/M/DD",
  "YYYY/MM/D",
  "YYYY/MM/DD",
  "DD/MM/YY",

  "D-M-YYYY",
  "D-MM-YYYY",
  "DD-M-YYYY",
  "DD-MM-YYYY",
  "DD-MMM-YYYY",
  "DD-MMMM-YYYY",
  "M-D-YYYY",
  "M-DD-YYYY",
  "MM-D-YYYY",
  "MM-DD-YYYY",
  "MMM-DD-YYYY",
  "MMMM-DD-YYYY",
  "YYYY-M-D",
  "YYYY-M-DD",
  "YYYY-MM-D",
  "YYYY-MM-DD",
  "YYYY-MMM-DD",
  "YYYY-MMMM-DD",
  "DD-MM-YY",

  "D MMM, YYYY",
  "DD MMM, YYYY",
  "D MMMM, YYYY",
  "DD MMMM, YYYY",
  "MMM D, YYYY",
  "MMM DD, YYYY",
  "MMMM D, YYYY",
  "MMMM DD, YYYY",
  "YYYY, MMM D",
  "YYYY, MMM DD",
  "YYYY, MMMM D",
  "YYYY, MMMM DD",

  "DD.MM.YYYY",
  "DDMMYYYY",
  "DDMMMYYYY",
  "MMDDYYYY",
  "MMMDDYYYY",
  "YYYYMMDD",
  "YYYYMMMDD",
  "DDD/YYYY",
  "YYYY/DDD",
]
